### ISSUE TITLE
HTTP Bindings

### ISSUE THREAD

**Issue by dthaler** [ietf-teep/teep-over-http#2]
[moved from https://github.com/ietf-teep/OTrP/issues/14]

@cyberphone reported:
It seems that cloud based TEEs and client based TEEs would work differently (protocol wise) during provisioning, at least when HTTP is used as transport.

**Client based TEE:**
Request is coming from the client side (outbound) which means that the TAM request data must be delivered in a HTTP response body while the TEE response is delivered in a subsequent HTTP POST request.

**Cloud based TEE:**
Request is coming from an outside service in the from of an HTTP POST request while the TEE response is returned in the associated HTTP response body.

Another difference is that in a cloud based scenario, the requester (TAM) must also be authenticated as a legitimate cloud service account user. This is a part of an HTTP binding scheme as well.

**Comment by dthaler** [comment]
I'm certainly open to the possibility if there are multiple vendors/service providers who would need this.  Folks I've talked to so far don't seem to have a need for OTrP for a cloud TEE yet, so it may be ok to leave for a future document and concentrate on the immediate needs (since we have lots of doc work to do for OTrP for the current model) unless there's WG energy immediately.   OTrP, it seems to be, fits best when the entity that wants to install the TA is different from the entity that needs to authorize the installation of the TA, and also when there's a whitelist of what TAs are allowed to run.   For cloud deployments that use SGX without any whitelist (i.e., any enclave is ok if the machine/VM wants it) then OTrP may not be immediately required for short term scenarios.   Would like to hear from the WG though since I agree that hypothetically it can make sense.

**Comment by mingpeiwk** [comment]
I also feel that the primary case of TEEP is to address client based TEE. A cloud based TEE provisioning refinement is better left for future if there are any. On the other hand, if we consider TEEP Broker as the one to initialize provisioning of a TA, the flow is similar. TEEP Broker in a cloud based TEE would also post a TEE response as a HTTP request body to a TAM. The question may be how the TA installation is triggered in a cloud based TEE?

**Comment by dthaler** [comment]
Per discussion at last IETF, scoping this draft to only client-based TEE, and left server-based TEE to a separate document.  Updated title accordingly, and added explicit discussion of the two scenarios into this doc.
